experiment_name: "ObjectRegion_ExploitationOnly_ObservedOnly"
evaluation: "local"          # Options: ["local", "remote"]
reasoning: "both"            # Options: ["both", "room", "obj"]
scenegraph: "node"           # Options: ["node", "both"]
visualize: true             # Boolean flag
split_l: 18                   # Integer: Start index for splitting
split_r: 19                 # Integer: End index for splitting
score_wo_room: false         
score_wo_graph: false        # Boolean flag
score_wo_node: false         # Boolean flag
log_file: true

# Modules 
perception_module: "GTPerception"
planner_module: "ImagineNavPlanner"

# Utility function
utility:
  trade_off:
    exploitation: 1.0
    exploration: 0.0
  hierarchical:
    room: false             # Boolean flag
    region: true           # Boolean flag
    object: true           # Boolean flag
    perception_conf: false   # Boolean flag
  exploitation:
    mode: "graph"
  exploration:
    mode: "map" # "graph", "map", "geometric"
  prediction: false        # Boolean flag
  llm: "qwen2.5:7b"
